### ISSUE TITLE
Add .language command

### ISSUE THREAD

**Issue by Andre601** [Andre601/PurrBot#57]
The language command will allow server admins to set the language for their Guild.
That way can \*Purr* respond with german messages on one Guild while responding in English on another.

The main parts I have to add are the following:
- An automatic system that adds the missing `language` setting of the guild in the database (Should be easy)
- A system that knows what languages and their codes (e.g. English with en) are available to determine if a given input is valid.

**Comment by Katinor** [comment]
Language system is very good. But it is bored to move all paragraph to othee place! Hope i can help it as Korean script.

I saw other bots use it also. For example, Ayana also can change the language. But this setting is done per user, not server. So whenever i use Ayana, it say korean even im in english based server.
Anyway hope this feature will be released soon!

**Comment by Andre601** [comment]
The reason why I want to have it per-guild and not per-user (which would also be possible) is that it prevents huge confusion when a user runs a command like `.info`, the command is deleted and there is an embed with korean text that nobody except the user requesting it can read.
This would cause many people to ask "What does this mean?" or "What command was that?"

It is also easier in terms of moderation as mods will have it easier to understand if the text is written in their language instead of first translating it.

I appreciate your feedback, and I would love your contribution to the project.
Feel free to make a PR containing your translation to the [v2.5 branch](https://github.com/Andre601/PurrBot/tree/v2.5/src/main/resources/lang) which is all about the translations.
If it's good I'll merge it into the branch later on.

**Comment by Katinor** [comment]
Korean have lots of expression to show its personality, Even use another suffixes to others. Maybe ill ask many to you when i make that.

How about make it also as user based for using it when they use bot as direct message. It will make database so big also but just one more column will be okay.

**Comment by Andre601** [comment]
The bot doesn't support direct messages.
Commands only work in Guilds and only two commands can have their responses be sent in DM, which is not a valid point to add this.
I may rethink this in the next day, but for now, it stays as per-guild.

**Comment by Katinor** [comment]
Thanks for your answer. Ill research her personality.

2019년 12월 20일 (금) 오전 8:59, Andre_601 <notifications@github.com>님이 작성:

**Comment by Katinor** [comment]
Do you know any character who has similar personality with her?

**Comment by Andre601** [comment]
> Do you know any character who has similar personality with her?

I don't really understand what you mean with that, so most likely no.

**Comment by Andre601** [comment]
The language command is now implemented... The only thing left is to add the lang support to all commands and the messages.
