### ISSUE TITLE
Me need help

### ISSUE THREAD

**Issue by Andre601** [Andre601/PurrBot#8]
BOT no work HELP MEEE!!!!11!

**Comment by Andre601** [comment]
@dessant Sorry to bother you. (Hope you even get the tag lol.)

But it seems like the bot doesn't accept the label?
I set it in double quotes, but for a reason does it not notice it?
Is the bot perhaps even down?

**Comment by dessant** [comment]
@Andre601, the config seems fine. You're right, the bot is down and I have trouble loading the project on glitch.com to restart it. I'll update you here when Glitch starts working again.

**Comment by dessant** [comment]
The app should work as expected now.

**Comment by Andre601** [comment]
uhm..... Why does it run on Glitch tho....

**Comment by dessant** [comment]
Where do you host your bots?

**Comment by Andre601** [comment]
I run mine on [deploys.io](https://deploys.io) on a VPS.
They also offer hostings for bots of all sorts.

**Comment by dessant** [comment]
They have interesting offers, I'll look into it. Thanks for the tip!
